name: Build application

on:
  push:
    branches:
    - main

jobs:
  build-ubuntu:
    name: Build app on Ubuntu
    uses: saru1604/reuseablerepo/.github/workflows/compliance.yml@main
    with:
      runs-on: ubuntu-latest
      run-tests: false
      project-folder: src
      artifact-name: drop-ubuntu
